### ISSUE TITLE
Get all traders

### ISSUE THREAD

**Issue by WagnerCenteio** [WebFintech34/mmo#10]
* Create the route
* Create controller endpoint
* Implement logic in trader user model to retrieve all traders
* Trader fields: fullname, gender, email, picture, password, phoneNumber, birthdate, location, traddingStyle, yearsOfExperience, brokersUsed, isCommitedToEndScams

**Comment by wilfredmulenga** [comment]
@WagnerCenteio  can I get this issue?

**Comment by WagnerCenteio** [comment]
@WillzMu its yours
