### ISSUE TITLE
Get all Investors

### ISSUE THREAD

**Issue by WagnerCenteio** [WebFintech34/mmo#11]
* Create a route
* Create a controller endpoint
* Implement logic in investor user model to retrieve all investors
* Investor fields: name, gender, email, picture, password, phoneNumber, age, location, isNewbie, amountWillingToRisc, isAwareOfScams, hasBeenScammed

**Comment by wilfredmulenga** [comment]
Thanks @WagnerCenteio. Question. What are the possible fields we would need for the investors table?

**Comment by WagnerCenteio** [comment]
> Thanks @WagnerCenteio. Question. What are the possible fields we would need for the investors table?

I've updated the issue with fields for the investors, and since we are going to use MongoDb there is no concept of tables, but rather documents and colections...

**Comment by wilfredmulenga** [comment]
Alright, thanks. let me work on it

**Comment by WagnerCenteio** [comment]
great

**Comment by wilfredmulenga** [comment]
Can we close this issue as well?

**Comment by WagnerCenteio** [comment]
> Can we close this issue as well?

Wich pull request is linked to it?
