### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by WagnerCenteio** [WebFintech34/mmo#12]
The user should login with ```email``` and ```password``` and a token generated  for successful login else throw respective error messages.
use the jwt format (with expiration)
Verify if user has access, if yes deliver token (JWT) to client for usage in subsequent requests

**Comment by wilfredmulenga** [comment]
@WagnerCenteio  can I take this one up?

**Comment by WagnerCenteio** [comment]
> @WagnerCenteio can I take this one up?
Sure, but i guess would be nice to first setup token based auth (JWT) issue, only then this one issue, right?

**Comment by wilfredmulenga** [comment]
Sounds okay, to me. If you could assign it to me and I can have a look

**Comment by WagnerCenteio** [comment]
> Sounds okay, to me. If you could assign it to me and I can have a look

good, and assigned

**Comment by wilfredmulenga** [comment]
I think we can close this issue
