### ISSUE TITLE
Trader user registration

### ISSUE THREAD

**Issue by WagnerCenteio** [WebFintech34/mmo#9]
* Create the route
* Create controller endpoint
* Implement logic in trader user model to save user data into the database
         ```fields : fullname, gender, email, password, phoneNumber, birthdate, picture, location, traddingStyle, yearsOfExperience, brokersUsed, isCommitedToEndScams```
* Passwords must be hashed using bcryptjs

**Comment by wilfredmulenga** [comment]
@WagnerCenteio  can I claim this issue?

**Comment by WagnerCenteio** [comment]
It's already assigned but if the @hbshofela didn't start yet i guess you can
